### ISSUE TITLE
Umbrella REST API "POST /api-umbrella/v1/users" fails with Umbrella 0.11

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#217] opened 2016-02-11 10:36 UTC
We are using Umbrella Admin API in https://github.com/apinf/api-umbrella-dashboard project.

POST data sent: 
```
{ 
  "user": {
     "email":  "test.user@email.com",
     "first_name": "-",
     "last_name": "-",
     "terms_and_conditions": true 
}
```
Everything else works with Umbrella Admin API, but creating user fails with 403 Forbidden:
```
{
  "error": {
    "code": "API_KEY_UNAUTHORIZED",
    "message": "The api_key supplied is not authorized to access the given service. Contact us at https://nightly.umbrella.apinf.io/contact/ for assistance"
  }
}
```

**Comment by jykae** [comment] 2016-02-11 10:41
I used the same email address for generating API Key that I have in my admin account.

**Comment by jykae** [comment] 2016-02-11 13:38
Tried using API key that Umbrella uses for internal Ajax requests, that works. Did not change my admin auth token. 
Normal API key doesn't work for creating user. There seems to be no relation with email address like we thought.

**Comment by GUI** [comment] 2016-02-11 14:07
The API key you use to create other API keys will need to have the `api-umbrella-key-creator` role assigned to it. If you assign that role to the key in the admin and save, then I think you should fix the 403 forbidden issues. However, if that doesn't do the trick, let us know.

If that does work, though, I'd be interested: Is the key you're using one that you previously were able to create API keys with before the API Umbrella upgrade? This role requirement should have always been in place, but if that role requirement wasn't actually functioning as intended under your previous installation, I want to be sure we flag that as an upgrade compatibility note.

**Comment by jykae** [comment] 2016-02-11 14:17
Thank you for the answer.

This installation is fresh installation of Umbrella v0.11 to be used just for our nightly builds of api-umbrella-dashboard. I will try the first trick, and let you know if it works.

**Comment by jykae** [comment] 2016-02-11 14:21
That did the trick, thanks.

**Comment by brylie** [comment] 2016-02-12 08:24
@GUI, thanks for the quick response and support.

The underlying issue here, having to assign superuser accounts with an additional `api-umbrella-key-creator` role, may be a regression. I.e. in 0.8, and semantically (see below), superuser accounts have *all permissions*.

> superuser account is capable of unrestricted, potentially adverse, system-wide changes. ([Wikipedia](https://en.wikipedia.org/wiki/Superuser))

**Comment by jykae** [comment] 2016-02-12 14:26
Just a note here for @GUI Today we successfully upgraded from v0.8 -> v0.11

Steps I needed to do after "sudo apt-get api-umbrella upgrade":
* add nginx server_names_hash_bucket_size 128 to config, resolved #208
* add "api-umbrella-key-creator" role to the API key that we use to create new API keys in api-umbrella-dashboard

**Comment by brylie** [comment] 2016-02-23 08:50
This issue is affecting our entire team and our [integration on our nightly deployment](https://github.com/apinf/api-umbrella-dashboard/issues/891#issuecomment-187587757). When setting up a development environment for new developers, we added the required permissions to their API User account, but were unable to launch the application. Also, on our nightly deployment server, we cannot create new users.

In both cases, there is an API call being made to the Admin API. Our integration code has not changed recently, but the API Umbrella version has been upgraded on the staging server.

**Comment by brylie** [comment] 2016-02-23 11:45
On our project issue tracker, I posted steps to reproduce. This seems to involve newly created users, as previously existing users (from our 0.8 upgrade) are working correctly.

# Steps to reproduce
1. Log in to API Umbrella (0.11 @ nightly.umbrella.apinf.io)
2. Go to Users -> Admin Accounts
3. Create a new admin user
  * check 'superuser' box
4. Go to Users -> API Users
5. Click 'Add New API User'
6. Create new API user with same email as admin user
  * Under Permissions -> Roles, add `api-umbrella-key-creator`
7. Sign-in with new Admin user
8. Get `API Key` and `Admin API Token` for new user
9. Add API Key and Admin API Token to settings.json
10. Launch Apinf
11. Register a new user

# Observed behavior
When registering a new user, the screen displays an **Internal server error** message. In the server console, the following error appears:

```sh
Exception while invoking method 'ATCreateUserServer' Error
     at new ApiUmbrellaError (packages/brylie_api-umbrella/server/apiUmbrellaError.js:33:1)
     at Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1)
   ...
```

The main issue is related to the following line `Object.self.adminApi.v1.apiUsers.createUser (packages/brylie_api-umbrella/server/apiUmbrellaWeb.js:275:1`, where we are trying to create an user on API Umbrella

**Comment by GUI** [comment] 2016-03-01 06:12
@brylie: Sorry for the delay. You're right that I think this is a regression when an admin account is being used. That wasn't a scenario we were explicitly testing for, but I think you're right that an admin account should be able to create users regardless of the roles associated with their API key. We'll try to get that fixed this week along with adding test coverage for this scenario.

If you're looking for a quick fix, I believe you could temporarily work around it by editing the `/opt/api-umbrella/embedded/apps/core/current/config/default.yml` file and removing [lines 300-302](https://github.com/NREL/api-umbrella/blob/v0.11.0/config/default.yml#L300-L302).

**Comment by GUI** [comment] 2016-03-08 06:09
Resolved in https://github.com/NREL/api-umbrella/commit/0cd7b88b00ad2cf1150628a9d52a4b9532259a6c Apologies for the regression, but thanks for letting us know. We now have better test coverage around this specific behavior.

We'll probably try to get v0.11.1 packages released early next week that will include this patch along with a few other bug fixes.

**Closed** 2016-06-26 17:25 UTC
