### ISSUE TITLE
module 'yaml.version' not found

### ISSUE THREAD

**Issue by puntofisso** [NREL/api-umbrella#250] opened 2016-06-12 14:13 UTC
I'm on Ubuntu Trusty (14.04). I've followed the tutorial but I keep getting this error.
Note that I've installed yaml via apt-get, pip, and also cpan (just to be sure...) but this hasn't changed it. Googling isn't of much help, and no one else mentions this error. What's happening?

```
# /etc/init.d/api-umbrella start
 * Starting API Umbrella api-umbrella                                                                                                                                       module 'yaml.version' not found:
	no field package.preload['yaml.version']
	no file '/opt/api-umbrella/embedded/apps/core/current/src/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file './yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file './yaml/version.so'
	no file '/usr/local/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.version' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
module 'yaml.parser' not found:
	no field package.preload['yaml.parser']
	no file '/opt/api-umbrella/embedded/apps/core/current/src/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/parser/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/parser/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/parser/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/parser/init.lua'
	no file './yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/parser.lua'
	no file '/usr/local/share/lua/5.1/yaml/parser.lua'
	no file '/usr/local/share/lua/5.1/yaml/parser/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/parser.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/parser/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/parser.so'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/parser.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/parser.so'
	no file './yaml/parser.so'
	no file '/usr/local/lib/lua/5.1/yaml/parser.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/parser.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.parser' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
luajit: ...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:429: attempt to call field 'parser' (a nil value)
stack traceback:
	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:429: in function 'Parser'
	...mbedded/apps/core/current/vendor/share/lua/5.1/lyaml.lua:456: in function 'load'
	...d/apps/core/current/src/api-umbrella/cli/read_config.lua:111: in function 'read_default_config'
	...d/apps/core/current/src/api-umbrella/cli/read_config.lua:367: in function 'read_config'
	...mbedded/apps/core/current/src/api-umbrella/cli/setup.lua:296: in function 'setup'
	.../embedded/apps/core/current/src/api-umbrella/cli/run.lua:39: in function 'run'
	...ella/embedded/apps/core/current/src/api-umbrella/cli.lua:13: in function 'command_function'
	...ella/embedded/apps/core/current/src/api-umbrella/cli.lua:130: in function 'cli'
	...umbrella/embedded/apps/core/current/bin/api-umbrella-cli:28: in main chunk
	[C]: at 0x00404e10
```

**Comment by GUI** [comment] 2016-06-12 15:05
I haven't seen this before, but hopefully we can get to the bottom of it. A few questions:

- Have you installed API Umbrella from the binary packages via apt-get? Or have you installed it via any other means (compiling from source)?
- What version of API Umbrella do you have installed (you can find this by running `api-umbrella --version`)?
- Can you provide the output of running `ls -l /opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so`
- Can you also provide the output of running `dpkg -l | grep -E "(yaml|umbrella)"`

**Comment by puntofisso** [comment] 2016-06-13 16:27
Hi Nick, thanks a lot for the reply and here's my questions.

I installed API-Umbrella from apt-get, just by following the guide at [https://apiumbrella.io/install/] and following the instruction for Ubuntu Trusty (14.04)

The version installed is 0.11.1

Output of ls: 
`-rwxr-xr-x 1 api-umbrella-deploy api-umbrella-deploy 102136 Apr 15 01:16 /opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so`

Output of dpkg:
```
ii  api-umbrella                             0.11.1-1~trusty                  amd64        no description given
ii  libyaml-0-2:amd64                        0.1.4-3ubuntu3.1                 amd64        Fast YAML 1.1 parser and emitter library
ii  python-yaml                              3.10-4ubuntu0.1                  amd64        YAML parser and emitter for Python
```

Let me know if there's anything wrong, or if you need any more information. Thanks!

**Comment by GUI** [comment] 2016-06-14 02:06
Hm, this is really strange. Everything looks correct, but based on the error you're getting, it appears like it's having trouble loading the `yaml.so` binary. But I just tested the API Umbrella 0.11.1 packages against a fresh Ubuntu 14.04 VM and I can't reproduce this.

The only dependency on that `yaml.so` binary should be the `libyaml-0-2` package that is an api-umbrella package dependency (and you do appear to have installed). So my only thought is that something else on your system might be getting picked up beforehand and causing this to fail. Out of curiosity, is this an existing Ubuntu 14.04 instance, or is it a fresh install?

In any case, it would still be great to figure out what's going on here. So if you don't mind some additional debugging, can you try running this [lyaml-test.sh](https://gist.github.com/GUI/241961ee59a09a797553cb54469e4abf) script? You can download the file or paste its contents into a file and then run `bash lyaml-test.sh`. If you could then share the output, I'm hoping one of those commands will at least help narrow down what's causing the issue in your environment.

**Comment by puntofisso** [comment] 2016-06-14 10:57
Hi Nick,
here's the output. Some interesting pointers in here:

```
+ file /opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so
/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=67611858776953781418d7d5803b695cfb78ed2a, not stripped
+ ldd /opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so
	linux-vdso.so.1 =>  (0x00007ffebe3fc000)
	libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 (0x00007f9d5b6de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d5b319000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559d6fca5000)
+ grep lua_package /opt/api-umbrella/etc/nginx/router.conf
grep: /opt/api-umbrella/etc/nginx/router.conf: No such file or directory
+ env PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin luajit -e 'print(package.path)'
./?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua
+ env -i PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin luajit -e 'print(package.path)'
./?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua
+ env PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin luajit -e 'print(package.cpath)'
./?.so;/usr/local/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
+ env -i PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin luajit -e 'print(package.cpath)'
./?.so;/usr/local/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
+ env PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin 'LUA_CPATH=/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/?.so' luajit -e 'local yaml = require "yaml"; print(yaml.version)'
luajit: /usr/local/share/lua/5.1/yaml/init.lua:26: module 'yaml.core' not found:
	no field package.preload['yaml.core']
	no file './yaml/core.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/core.lua'
	no file '/usr/local/share/lua/5.1/yaml/core.lua'
	no file '/usr/local/share/lua/5.1/yaml/core/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/core.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/core/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/core.so'
	no module 'yaml.core' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/yaml/init.lua:26: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00404e10
+ env -i PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin 'LUA_CPATH=/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/?.so' luajit -e 'local yaml = require "yaml"; print(yaml.version)'
luajit: /usr/local/share/lua/5.1/yaml/init.lua:26: module 'yaml.core' not found:
	no field package.preload['yaml.core']
	no file './yaml/core.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/core.lua'
	no file '/usr/local/share/lua/5.1/yaml/core.lua'
	no file '/usr/local/share/lua/5.1/yaml/core/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/core.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/core/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/core.so'
	no module 'yaml.core' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/yaml/init.lua:26: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00404e10
+ env PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin 'LUA_PATH=/opt/api-umbrella/embedded/apps/core/current/src/?.lua;/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/lualib/?.lua;/opt/api-umbrella/embedded/openresty/lualib/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua;./?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua' 'LUA_CPATH=/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/lualib/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so' luajit -e 'local yaml = require "yaml"; print(yaml.version)'
module 'yaml.version' not found:
	no field package.preload['yaml.version']
	no file '/opt/api-umbrella/embedded/apps/core/current/src/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file './yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file './yaml/version.so'
	no file '/usr/local/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.version' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
nil
+ env -i PATH=/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin 'LUA_PATH=/opt/api-umbrella/embedded/apps/core/current/src/?.lua;/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/lualib/?.lua;/opt/api-umbrella/embedded/openresty/lualib/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua;./?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?.lua;/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/?/init.lua' 'LUA_CPATH=/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/lualib/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so' luajit -e 'local yaml = require "yaml"; print(yaml.version)'
module 'yaml.version' not found:
	no field package.preload['yaml.version']
	no file '/opt/api-umbrella/embedded/apps/core/current/src/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file './yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/luajit-2.1.0-beta1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version.lua'
	no file '/usr/local/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version.lua'
	no file '/opt/api-umbrella/embedded/openresty/luajit/share/lua/5.1/yaml/version/init.lua'
	no file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/lualib/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file './yaml/version.so'
	no file '/usr/local/lib/lua/5.1/yaml/version.so'
	no file '/opt/api-umbrella/embedded/openresty/luajit/lib/lua/5.1/yaml/version.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'yaml.version' in file '/opt/api-umbrella/embedded/apps/core/current/vendor/lib/lua/5.1/yaml.so'
nil
```

**Comment by GUI** [comment] 2016-06-14 14:19
Ah, perfect, this helps. It looks like there's a conflicting Lua YAML library that's installed on your system at `/usr/local/share/lua/5.1/yaml/init.lua`. But this is useful to know about, since we explicitly try to load the API Umbrella dependencies before anything else to prevent these kind of issues. However, it looks like under certain circumstances, the libraries installed on the system can still cause conflicts.

I think fixing this issue within API Umbrella should be fairly easy so we can co-exist with other Lua libraries installed on the same system (we'll just need to load our Lua dependencies in a more isolated fashion than we were before). Could you try replacing the contents of `/opt/api-umbrella/embedded/apps/core/current/bin/api-umbrella-cli ` on your system with:

```lua
#!/usr/bin/env luajit

local embedded_root = os.getenv("API_UMBRELLA_EMBEDDED_ROOT")
if embedded_root then
  package.path = embedded_root .. "/openresty/lualib/?.lua;" ..
    embedded_root .. "/openresty/lualib/?/init.lua;" ..
    embedded_root .. "/openresty/luajit/share/luajit-2.1.0-beta1/?.lua;" ..
    embedded_root .. "/openresty/luajit/share/luajit-2.1.0-beta1/?/init.lua;" ..
    embedded_root .. "/openresty/luajit/share/lua/5.1/?.lua;" ..
    embedded_root .. "/openresty/luajit/share/lua/5.1/?/init.lua"
  package.cpath = embedded_root .. "/openresty/lualib/?.so;" ..
    embedded_root .. "/openresty/luajit/lib/lua/5.1/?.so"
end

local src_root = os.getenv("API_UMBRELLA_SRC_ROOT")
if src_root then
  package.path = src_root .. "/src/?.lua;" ..
    src_root .. "/vendor/share/lua/5.1/?.lua;" ..
    src_root .. "/vendor/share/lua/5.1/?/init.lua;" ..
    package.path
  package.cpath = src_root .. "/vendor/lib/lua/5.1/?.so;" ..
    package.cpath
end

local cli = require "api-umbrella.cli"
cli()
```

If you have a chance to give that a try and could let us know whether or not it fixes the startup issue for you, that would be a big help. If it does fix things, then we'll get that fix integrated into the next release.

Thanks for your help debugging this!

**Comment by puntofisso** [comment] 2016-06-14 14:40
Hi Nick,
that fixed the issue and the instance is now available. Let me know if you push a definitive patch to the apt-get process.
If you want, this issue can be considered close, unless you want to keep it open as a reminder until you apply a patch.
G

**Comment by GUI** [comment] 2016-06-15 03:26
I've committed a fix to master for this. This will be part of the next v0.12 package release. We don't currently have a release date for that package release, but hopefully it shouldn't be too far off. Feel free to watch this repo or subscribe to the [mailing list](https://groups.google.com/forum/#!forum/api-umbrella) for an announcement when it's released.

**Closed by GUI** 2016-06-15 03:26 UTC

**Comment by GUI** [comment] 2016-06-30 15:25
Quick heads up: v0.12.0 packages have been [released](https://groups.google.com/forum/#!topic/api-umbrella/x5GfWdnho1M), which includes this update.

**Comment by puntofisso** [comment] 2016-06-30 15:26
Thanks Nick!

*--*
*Giuseppe Sollazzo*
www.puntofisso.net
@puntofisso

Director, Puntofisso Ltd | CTO, DigitailComics.com
*JISC's 50 most influential Higher Education professionals on social media
<https://www.jisc.ac.uk/blog/uk-higher-education-social-media-influencers-named-05-oct-2015>*


*Subscribe to my weekly "In other news": http://puntofisso.net/newsletter
<http://puntofisso.net/newsletter>*
